#!/bin/bash


input_dir=./input_images
images=$(ls $input_dir | grep -E "*.(jpg|png|bmp)")
output_dir=./output_images
filter=$1
repetitions=$2

echo "image;threads;seconds" > results_graphs.txt

for i in $images; do
    for ((t=1; t<=16; t=2*t)) do
        printf "\nExecuting the filter for image $i with $t threads $repetitions times:\n";
        for ((r=0; r<$repetitions; r++)) do
            $filter $input_dir/$i $output_dir/${t}_${i} $t | awk -F ": " -v a=$i -v b=$t '{if(NR==2) printf "%s;%s;%s\n", a, b, $2 }' >> results_graphs.txt;
        done
    done
done
