#!/bin/bash

input_dir=./input_images
images=$(ls $input_dir)
output_dir=./output_images
filter=./mypc_hilos

for i in $images; do
    for ((t=1; t<=16; t=2*t)) do
        printf "\nExecuting the filter for image $i with $t threads:\n" | tee -a results.txt;
        $filter $input_dir/$i $output_dir/${t}_${i} $t | tee -a results.txt;
    done
done

